import urllib.request,urllib.parse,http.cookiejar,re,json,uuid,zipfile,io
base='http://127.0.0.1:8097'
data=json.load(open('work/fixture.json'))
results=[]
class Client:
 def __init__(self): self.opener=urllib.request.build_opener(urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()));self.token=None
 def get(self,path):
  try:
   with self.opener.open(base+path) as r: body=r.read().decode(); status=r.status
  except urllib.error.HTTPError as e: body=e.read().decode(); status=e.code
  m=re.search(r'name="_csrf" value="([a-f0-9]+)"',body)
  if m:self.token=m[1]
  assert 'Fatal error' not in body and 'Warning:' not in body,body[:500]
  return status,body
 def post(self,path,values,csrf=True):
  if csrf:values={'_csrf':self.token,**values}
  req=urllib.request.Request(base+path,urllib.parse.urlencode(values).encode())
  try:
   with self.opener.open(req) as r: body=r.read().decode();status=r.status
  except urllib.error.HTTPError as e:body=e.read().decode();status=e.code
  m=re.search(r'name="_csrf" value="([a-f0-9]+)"',body)
  if m:self.token=m[1]
  assert 'Fatal error' not in body and 'Warning:' not in body,body[:500]
  return status,body
 def login(self,email): self.get('/login');return self.post('/login',{'email':email,'password':'TestPassword123!'})
 def upload(self,path,values,field,filename,content,mime):
  boundary='Boundary'+uuid.uuid4().hex;body=bytearray()
  for key,value in {'_csrf':self.token,**values}.items():body.extend(('--'+boundary+'\r\nContent-Disposition: form-data; name="'+key+'"\r\n\r\n'+str(value)+'\r\n').encode())
  body.extend(('--'+boundary+'\r\nContent-Disposition: form-data; name="'+field+'"; filename="'+filename+'"\r\nContent-Type: '+mime+'\r\n\r\n').encode());body.extend(content);body.extend(('\r\n--'+boundary+'--\r\n').encode())
  req=urllib.request.Request(base+path,body,headers={'Content-Type':'multipart/form-data; boundary='+boundary})
  try:
   with self.opener.open(req) as r:result=r.read().decode();status=r.status
  except urllib.error.HTTPError as e:result=e.read().decode();status=e.code
  assert 'Fatal error' not in result and 'Warning:' not in result,result[:500]
  return status,result
def check(label,condition):
 assert condition,label
 results.append(label);print('PASS',label,flush=True)
admin=Client();check('Admin login',admin.login('admin@test.invalid')[0]==200)
admin.post('/select-project',{'job_id':data['a']})
for path in ['/','/projects','/job','/candidates','/roster','/hotels','/travel','/hours','/billing','/people','/onboarding','/operations','/account','/overview','/manning','/organization','/learning','/comms','/notifications','/settings','/timeoff','/agreements','/inbox','/proofs','/employment','/checks','/recruitment','/personnel','/imports','/expenses','/accounts-payable','/payroll-export','/client-invoices','/attendance']:
 check('Render '+path,admin.get(path)[0]==200)
check('CSRF rejected',admin.post('/projects',{'title':'Invalid','client':'Invalid'},False)[0]==419)
worker=Client();check('Worker login and private portal',worker.login('worker@test.invalid')[0]==200)
body=worker.get('/portal')[1];check('Worker data isolation','worker2@test.invalid' not in body)
check('Worker staff route redirected to portal','Your assignments' in worker.get('/people')[1])
_,body=admin.post('/roster',{'do':'status','placement_id':data['ids'][0]['placement'],'status':'on_site'})
check('Incomplete onboarding blocks deployment','onboarding tasks approved' in body or 'Configure and approve' in body)
worker.post('/portal',{'task_id':data['task'],'response':'Orientation complete'})
admin.post('/onboarding',{'do':'review','task_id':data['task'],'status':'approved'})
admin.post('/roster',{'do':'status','placement_id':data['ids'][0]['placement'],'status':'on_site'})
booking={'do':'book','placement_id':data['ids'][0]['placement'],'hotel_id':data['hotel'],'room_number':'212','check_in':'2026-10-10','check_out':'2026-10-15','private_room':'1'}
check('Hotel booking',admin.post('/hotels',booking)[0]==200)
_,body=admin.post('/hotels',{**booking,'placement_id':data['ids'][1]['placement']})
check('Overlapping room blocked','during these dates' in body)
_,body=admin.post('/hotels',{**booking,'placement_id':data['ids'][1]['placement'],'check_in':'2026-10-15','check_out':'2026-10-20'})
check('Sequential room reuse allowed','booked into' in body)
_,body=admin.post('/hotels',{**booking,'private_room':'','check_out':'2026-10-09'})
check('Invalid date interval blocked','valid check-in/out dates' in body)
admin.post('/operations',{'do':'passenger','placement_id':data['ids'][0]['placement'],'run_id':data['run'],'pickup_stop':'Lobby'})
_,body=admin.post('/operations',{'do':'passenger','placement_id':data['ids'][1]['placement'],'run_id':data['run'],'pickup_stop':'Lobby'})
check('Route capacity enforced','vehicle full' in body)
admin.post('/operations',{'do':'issue','placement_id':data['ids'][0]['placement'],'equipment_id':data['asset']})
_,body=admin.post('/operations',{'do':'issue','placement_id':data['ids'][1]['placement'],'equipment_id':data['asset']})
check('Double equipment issue blocked','Equipment is unavailable' in body)
_,body=admin.post('/operations',{'do':'offboard','placement_id':data['ids'][0]['placement']})
check('Offboarding requires equipment return','Return outstanding equipment' in body)
_,body=admin.post('/hours',{'do':'save','week_ending':'2026-10-17',f"hours[{data['ids'][0]['placement']}]":'41',f"per_diem[{data['ids'][0]['placement']}]":'7',f"expenses[{data['ids'][0]['placement']}]":'0'})
check('Guarantee arithmetic','$2,710.00' in body)
admin.post('/hours',{'do':'approve_week','week_ending':'2026-10-17'})
admin.post('/hours',{'do':'save','week_ending':'2026-10-17',f"hours[{data['ids'][0]['placement']}]":'99'})
check('Approved timesheet immutable','value="41"' in admin.get('/hours?week=2026-10-17')[1])
admin.post('/hours',{'do':'save','week_ending':'2026-10-24',f"hours[{data['pb']}]":'99'})
admin.post('/select-project',{'job_id':data['b']})
check('Cross-project timesheet injection blocked','value="99"' not in admin.get('/hours?week=2026-10-24')[1])
public=Client();public.get('/apply?id='+str(data['vac']))
check('Public application accepted','Application received' in public.post('/apply',{'vacancy_id':data['vac'],'name':'Public applicant','email':'applicant@test.invalid','consent':'1'})[1])
invite=Client();invite.get('/activate?token='+data['token'])
check('Invitation activation',invite.post('/activate',{'token':data['token'],'password':'UniquePassword123!'})[0]==200)
check('Invitation cannot be reused',invite.get('/activate?token='+data['token'])[0]==410)
check('GET logout rejected',admin.get('/logout')[0]==405)
admin.post('/select-project',{'job_id':data['a']})
worker.get('/proofs')
_,body=worker.upload('/proofs',{'do':'upload','document_type':'Receipt'},'proof','receipt.pdf',b'%PDF-1.4\nSynthetic test receipt\n%%EOF','application/pdf')
check('Encrypted proof upload', 'Receipt' in body)
doc_id=int(re.search(r'/proofs\?download=(\d+)',body).group(1))
worker2=Client();worker2.login('worker2@test.invalid')
check('Other worker cannot download proof',worker2.get('/proofs?download='+str(doc_id))[0]==404)
# Free text is no longer a kind of leave.
_,refused=worker.post('/timeoff',{'do':'request','placement_id':data['ids'][0]['placement'],'starts_on':'2026-10-21','ends_on':'2026-10-22','request_type':'Personal leave'})
check('Time off needs a kind from the catalogue','Choose what kind' in refused)
worker.post('/timeoff',{'do':'request','placement_id':data['ids'][0]['placement'],'starts_on':'2026-10-21','ends_on':'2026-10-22','leave_type':'personal','reason':'Family'})
_,body=admin.get('/timeoff');request_id=int(re.search(r'name="request_id" value="(\d+)"',body).group(1))
supervisor=Client();check('Supervisor login and private team',supervisor.login('supervisor@test.invalid')[0]==200)
supervisor.get('/timeoff');supervisor.post('/timeoff',{'do':'review','request_id':request_id,'status':'approved','review_note':'Approved'})
check('Supervisor approves own team time-off','Approved' in worker.get('/timeoff')[1])
_,body=admin.post('/comms',{'do':'channel','name':'Supervisors coordination'})
channel_id=int(re.search(r'/comms\?channel_id=(\d+)',body).group(1))
admin.post('/comms',{'do':'member','channel_id':channel_id,'user_id':data['ids'][0]['user']})
admin.post('/comms',{'do':'message','channel_id':channel_id,'message':'Meet in the lobby at 07:00.'})
check('Private channel delivery','Meet in the lobby' in worker.get('/comms?channel_id='+str(channel_id))[1])
check('Channel membership isolates messages','Meet in the lobby' not in worker2.get('/comms?channel_id='+str(channel_id))[1])
check('Notification delivered','New channel message' in worker.get('/notifications')[1])
admin.post('/learning',{'do':'content','kind':'training','title':'Site induction','content':'Read the site safety briefing.'})
_,body=worker.get('/learning');content_id=int(re.search(r'name="content_id" value="(\d+)"',body).group(1))
worker.post('/learning',{'do':'complete','content_id':content_id})
check('Learning completion tracked','Completed' in worker.get('/learning')[1])
admin.post('/agreements',{'do':'issue','placement_id':data['ids'][0]['placement'],'title':'Deployment terms','document_text':'Synthetic approved deployment agreement.'})
_,body=worker.get('/agreements');agreement_id=int(re.search(r'name="document_id" value="(\d+)"',body).group(1))
worker.post('/agreements',{'do':'sign','document_id':agreement_id,'signer_name':'Test Worker','consent':'1'})
check('Electronic acknowledgement with timestamp',bool(re.search(r'signed[^<]*Test Worker[^<]*\d{4}-\d{2}-\d{2}',worker.get('/agreements')[1])))
admin.post('/checks',{'do':'issue','placement_id':data['ids'][0]['placement'],'kind':'drug','delivery_mode':'mobile_bus','payer':'worker_reimbursement','authorization_text':'Synthetic approved screening authorization.'})
_,body=admin.get('/checks');case_id=int(re.search(r'name="case_id" value="(\d+)"',body).group(1))
_,body=admin.post('/checks',{'do':'status','case_id':case_id,'status':'scheduled'})
check('Screening requires signed authorization','authorization must be signed' in body)
worker.post('/expenses',{'do':'claim','placement_id':data['ids'][0]['placement'],'category':'flight','amount':'250','receipt_document_id':doc_id,'note':'Flight reimbursement'})
_,body=admin.get('/expenses');claim_id=int(re.search(r'name="claim_id" value="(\d+)"',body).group(1))
admin.post('/expenses',{'do':'review','claim_id':claim_id,'status':'approved'})
admin.post('/expenses',{'do':'pay','claim_id':claim_id,'payment_method':'check','payment_reference':'CHK-TEST-01'})
check('Receipt reimbursement approval and payment','CHK-TEST-01' in worker.get('/expenses')[1])
admin.post('/accounts-payable',{'do':'invoice','vendor_name':'Test hotel','reference':'HOTEL-001','amount':'500','due_on':'2026-10-30'})
_,body=admin.get('/accounts-payable');vendor_id=int(re.search(r'name="invoice_id" value="(\d+)"',body).group(1))
admin.post('/accounts-payable',{'do':'approve','invoice_id':vendor_id})
admin.post('/accounts-payable',{'do':'pay','invoice_id':vendor_id,'payment_method':'transfer','payment_reference':'VENDOR-TEST-01'})
check('Vendor approval and payment','VENDOR-TEST-01' in admin.get('/accounts-payable')[1])
admin.post('/client-invoices',{'do':'generate','starts_on':'2026-10-17','ends_on':'2026-10-17'})
check('Frozen client invoice generated','$3,280.00' in admin.get('/client-invoices')[1])
_,body=admin.post('/client-invoices',{'do':'generate','starts_on':'2026-10-17','ends_on':'2026-10-17'})
check('Duplicate billing blocked','No uninvoiced approved sheets' in body)
check('ADP export requires configuration',admin.get('/payroll-export?week=2026-10-17&export=adp_run')[0]==422)
admin.get('/imports')
csv=b'Employee,Email,Phone,Trade\nImported Worker,imported@test.invalid,555-0100,Welder\nDuplicate Worker,worker@test.invalid,555-0101,Driver\n'
_,body=admin.upload('/imports',{'do':'preview'},'sheet','employees.csv',csv,'text/csv')
check('CSV import preview','employees.csv' in body)
_,body=admin.post('/imports',{'do':'commit','mapping[full_name]':'0','mapping[email]':'1','mapping[phone]':'2','mapping[trade]':'3'})
check('CSV import preserves duplicate for review','1 imported' in body and '1 duplicate reviews' in body)
xlsx=io.BytesIO()
with zipfile.ZipFile(xlsx,'w') as z:
 z.writestr('xl/workbook.xml','<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Employees" sheetId="1" r:id="rId1"/></sheets></workbook>')
 z.writestr('xl/_rels/workbook.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>')
 z.writestr('xl/worksheets/sheet1.xml','<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Employee</t></is></c></row><row r="2"><c r="A2" t="inlineStr"><is><t>XLSX Worker</t></is></c></row></sheetData></worksheet>')
_,body=admin.upload('/imports',{'do':'preview'},'sheet','employees.xlsx',xlsx.getvalue(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
check('XLSX import preview','XLSX Worker' in body)
_,body=admin.post('/imports',{'do':'commit','mapping[full_name]':'0'})
check('XLSX mapped import','employees.xlsx' in body)
public=Client();public.get('/apply?id='+str(data['vac']))
public.post('/apply',{'vacancy_id':data['vac'],'name':'Reapplying worker','email':'worker@test.invalid','consent':'1'})
check('Reapplication flags potential existing identity','Possible existing candidate' in admin.get('/recruitment')[1])
check('Historical rejection survives reconsideration','worker@test.invalid' in admin.get('/candidates?rejected_before=1')[1])
admin.post('/recruitment',{'do':'stage','application_id':data['historyApp'],'stage':'offered','note':'Synthetic offer terms: hourly role for project A.'})
check('Offer terms appear in private portal','Synthetic offer terms' in worker.get('/portal')[1])
_,offerBody=worker.post('/portal',{'do':'accept_offer','application_id':data['historyApp'],'signer_name':'Test worker','consent':'1'})
check('Signed offer acceptance completes','accepted' in offerBody and 'Synthetic offer terms' not in offerBody)
check('Employee directory renders',admin.get('/employees')[0]==200)
for route in ['/requisitions','/channels','/ai-review','/email-delivery','/structure']:
 check('New workspace screen '+route,admin.get(route)[0]==200)
check('Worker cannot open recruiting AI','Relevant welding experience' not in worker.get('/ai-review')[1] and 'AI review' not in worker.get('/ai-review')[1])
_,aiBody=admin.post('/ai-review',{'application_id':data['historyApp'],'evidence':'Relevant welding experience','reviewed_evidence':'1'})
check('AI requires configured provider','Configure and approve the AI provider' in aiBody)
_,noLine=admin.post('/requisitions',{'title':'Synthetic unbacked role','description':'Synthetic job requirements'})
check('Requisition without a line of the scope refused','Pick the line of the scope of work' in noLine)
check('Refused requisition was not created','Synthetic unbacked role' not in admin.get('/requisitions')[1])
admin.post('/requisitions',{'title':'Synthetic QR role','description':'Synthetic job requirements','order_line_id':data['lineLabour'],'openings':'1'})
check('Requisition creation renders QR', 'Synthetic QR role' in admin.get('/requisitions')[1])
check('Requisition inherits the rate agreed on its line','$22.00' in admin.get('/requisitions')[1])
_,overOrdered=admin.post('/requisitions',{'title':'Synthetic over-order','description':'Synthetic job requirements','order_line_id':data['lineLabour'],'openings':'5'})
check('Cannot order more of a trade than the agreement covers','only 0 can still be raised' in overOrdered)
# ── the scope of work ───────────────────────────────────────────────────
# An agreement is taken on, then its order is written trade by trade. Every
# figure below is worked out by hand:
#   20 engineers  x 50 h x $65 = $65,000 + 20 x 7 x $40  = $70,600
#   100 labourers x 40 h x $22 = $88,000 + 100 x 7 x $30 = $109,000
#   together                                             = $179,600
agreement={'title':'Scope test agreement','description':'Provide labour support to the test plant in accordance with the scope of work.','order_reference':'PO-SCOPE-1','site_name':'Test plant','site_city':'Gary','site_state':'IN','lodging_provided':'1','travel_provided':'1','status':'planning'}
admin.post('/projects',dict(agreement,client='Scope test client'))
_,scopeBody=admin.get('/job')
check('A new agreement has no scope yet','No scope written yet' in scopeBody)
check('The agreement carries its description','in accordance with the scope of work' in scopeBody)
check('The agreement carries what it covers','Lodging paid' in scopeBody)

admin.post('/job',{'do':'add_line','role_title':'Plant engineer','discipline':'mechanical','quantity':'20','shift':'Days, 12 hours','pay_rate':'65','bill_rate':'95','per_diem_rate':'40','guarantee_hours':'50','strike_guarantee_hours':'60'})
_,scopeBody=admin.get('/job')
check('A trade is on the order','Plant engineer' in scopeBody)
check('One line prices a full week','$70,600.00' in scopeBody)
check('The headcount asked for follows the order','total of the scope of work above: 20' in scopeBody)

admin.post('/job',{'do':'add_line','role_title':'General labourer','discipline':'other','quantity':'100','pay_rate':'22','bill_rate':'38','per_diem_rate':'30','guarantee_hours':'40'})
_,scopeBody=admin.get('/job')
check('Two trades at two rates sum, not one rate for everybody','$179,600.00' in scopeBody)
check('Both trades are listed','General labourer' in scopeBody and 'Plant engineer' in scopeBody)
check('The headcount asked for is the whole order','total of the scope of work above: 120' in scopeBody)

# An unpriced line stays on the order and is named as unpriced rather than
# counted as free.
admin.post('/job',{'do':'add_line','role_title':'Machinist','discipline':'other','quantity':'2000'})
_,scopeBody=admin.get('/job')
check('An unpriced line is on the order but not in the money','Not priced' in scopeBody and '$179,600.00' in scopeBody)
check('The gate names the unpriced lines','have no agreed pay rate' in scopeBody)

# Correcting a line, through the same form that wrote it.
scopeLines=re.findall(r'/job\?line=(\d+)',scopeBody)
check('Every line can be opened for correction',len(scopeLines)==3)
admin.post('/job',{'do':'save_line','line_id':scopeLines[0],'role_title':'Plant engineer','discipline':'mechanical','quantity':'10','pay_rate':'65','bill_rate':'95','per_diem_rate':'40','guarantee_hours':'50','strike_guarantee_hours':'60'})
check('A corrected quantity reprices the agreement','$144,300.00' in admin.get('/job')[1])

# A negative rate is refused, and the refusal names the term it belongs to.
_,badRate=admin.post('/job',{'do':'add_line','role_title':'Bad line','quantity':'1','pay_rate':'-5'})
check('An impossible rate is refused by name','Pay rate' in badRate and 'negative or impossible' in badRate)
check('The refused line was not written','Bad line' not in admin.get('/job')[1])

# The strike switch reprices from the lines:
#   10 engineers x 60 h x $65 = $39,000 + $2,800 per diem = $41,800
#   the labourers have no strike guarantee, so they stay on 40 h = $109,000
admin.post('/job',dict(agreement,strike_live='1'))
check('The strike switch reprices the agreement from its lines','$150,800.00' in admin.get('/job')[1])
admin.post('/job',dict(agreement))
check('Standing the strike down restores the normal guarantees','$144,300.00' in admin.get('/job')[1])

# A line with requisitions raised against it is kept, not deleted.
admin.post('/requisitions',{'title':'Scope test machinist','description':'Scope test requirements','order_line_id':scopeLines[2],'openings':'5'})
_,keptBody=admin.post('/job',{'do':'remove_line','line_id':scopeLines[2]})
check('A line with requisitions against it cannot be removed','requisitions were raised against that line' in keptBody)

# One with nothing raised against it can be.
admin.post('/job',{'do':'remove_line','line_id':scopeLines[1]})
check('A line nothing was raised against is removed','General labourer' not in admin.get('/job')[1])

# A line cannot be cut below the people already standing on the site.
admin.post('/select-project',{'job_id':data['a']})
_,shrunk=admin.post('/job',{'do':'save_line','line_id':data['lineWelder'],'role_title':'Test welder','discipline':'mechanical','quantity':'0','pay_rate':'50'})
check('A line cannot be ordered at nothing','How many of this trade' in shrunk)

_,recruitmentBody=admin.get('/recruitment')
publicApplication=re.search(r'Public applicant.*?name="application_id" value="(\d+)"',recruitmentBody,re.S)
check('Public application identifiable by recruiter',publicApplication is not None)
admin.post('/recruitment',{'do':'stage','application_id':publicApplication.group(1),'stage':'screening','note':'Review qualifications'})
_,queueBody=admin.get('/email-delivery')
check('Screening queues activation email','applicant@test.invalid' in queueBody)
admin.post('/recruitment',{'do':'stage','application_id':publicApplication.group(1),'stage':'screening','note':'Review again'})
check('Repeated screening does not duplicate invitation',admin.get('/email-delivery')[1].count('applicant@test.invalid')==1)
admin.post('/channels',{'vacancy_id':data['vac'],'channel':'indeed'})
check('Job board request is explicitly pending','Integration pending' in admin.get('/channels')[1])
check('Job feed contains no employee emails','worker@test.invalid' not in public.get('/job-feed')[1])
check('Subscription page renders',admin.get('/subscription')[0]==200)
check('Unsigned Stripe webhook rejected',public.post('/stripe-webhook',{},csrf=False)[0]==400)
check('GET Stripe webhook rejected',public.get('/stripe-webhook')[0]==405)
_,snapshotBody=admin.post('/subscription',{'do':'snapshot','month':'2026-09'})
check('Closed-month usage snapshot',snapshotBody.count('2026-09-01')==1)
check('POST logout succeeds',admin.post('/logout',{})[0]==200)
admin.login('admin@test.invalid');admin.post('/select-project',{'job_id':data['a']})
check('Client access administration renders',admin.get('/client-access')[0]==200)
admin.post('/client-orders',{'do':'create','client_id':data['client'],'title':'Email request for 600 welders','description':'Client requested welding crew by email; no client login.','source':'email','source_reference':'EMAIL-TEST-01','headcount':'600','site_city':'Houston','site_state':'TX'})
_,orderBody=admin.get('/client-orders');orderId=re.search(r'name="order_id" value="(\d+)"',orderBody).group(1)
check('Email request captured without client login','EMAIL-TEST-01' in orderBody)
admin.post('/client-orders',{'do':'update','order_id':orderId,'status':'approved','note':'Updated email instructions.','description':'Client now requests 700 welders, without any portal login.','headcount':'700'})
_,editedOrder=admin.get('/client-orders')
check('Office updates email request and preserves history','700 welders' in editedOrder and 'Updated email instructions.' in editedOrder and '600' in editedOrder)
check('Unapproved request cannot create project',admin.post('/client-orders',{'do':'convert','order_id':orderId})[0]==422)
admin.post('/client-orders',{'do':'update','order_id':orderId,'status':'approved','note':'Headcount and instructions confirmed.'})
check('Approved request creates project',admin.post('/client-orders',{'do':'convert','order_id':orderId})[0]==200)
check('Request cannot create duplicate project',admin.post('/client-orders',{'do':'convert','order_id':orderId})[0]==422)
client=Client();check('Client account signs in',client.login('client@test.invalid')[0]==200)
_,clientBody=client.get('/client-portal?job_id='+str(data['a']))
check('Client sees authorized project','Test project A' in clientBody)
check('Client sees email request in workspace','Email request for 600 welders' in clientBody)
check('Client cannot enumerate other client','Private other client project' not in clientBody and 'Other private client' not in clientBody)
check('Client cannot select other client project',client.get('/client-portal?job_id='+str(data['otherJob']))[0]==404)
check('Client cannot download other client invoice',client.get('/client-portal?job_id='+str(data['a'])+'&invoice_id='+str(data['otherInvoice']))[0]==404)
for forbidden in ['/employee-folder?id='+str(data['ids'][0]['candidate']),'/proofs','/payroll-export','/subscription','/select-project','/recruitment','/client-access']:
 check('Client blocked from private staff route '+forbidden,client.get(forbidden)[0]==403)
check('Client export excludes confidential fields','pay_rate' not in client.get('/client-portal?job_id='+str(data['a'])+'&export=attendance&from=2026-10-01&to=2026-10-31')[1])
_,attendanceBody=client.get('/client-portal?job_id='+str(data['a']))
attendanceMatch=re.search(r'name="attendance_id" value="(\d+)"',attendanceBody)
check('Client sees approved attendance for review',attendanceMatch is not None)
_,reviewBody=client.post('/client-portal',{'job_id':data['a'],'attendance_id':attendanceMatch.group(1),'decision':'disputed','note':'Please verify the start time.'})
check('Client can flag attendance without changing payroll','Please verify the start time.' in reviewBody)
check('Client rejects invalid attendance reference',client.post('/client-portal',{'job_id':data['a'],'attendance_id':'999999','decision':'confirmed'})[0]==404)
_,billBody=admin.get('/client-invoices');billId=re.search(r'name="invoice_id" value="(\d+)"',billBody).group(1)
admin.post('/client-invoices',{'do':'issue','invoice_id':billId})
check('Client can read issued invoice',client.get('/client-portal?job_id='+str(data['a'])+'&invoice_id='+billId)[0]==200)
admin.post('/language',{'locale':'fr','back':'/hotels'})
check('French composed hotel summary','chambres réservées' in admin.get('/hotels')[1])
_,frBody=admin.post('/account',{'current':'incorrect','new':'AValidPassword123','repeat':'AValidPassword123'})
check('French validation response','votre mot de passe actuel' in frBody)
admin.post('/logout',{});admin.login('admin@test.invalid')
check('Saved French survives fresh login','chambres réservées' in admin.get('/hotels')[1])
admin.post('/language',{'locale':'es','back':'/client-access'})
check('Spanish client administration','Acceso de clientes' in admin.get('/client-access')[1])
admin.post('/language',{'locale':'en','back':'/client-access'})
admin.post('/client-access',{'do':'revoke','client_id':data['client'],'user_id':data['clientUser']})
check('Revocation immediately prevents project access',client.get('/client-portal?job_id='+str(data['a']))[0]==404)

# Additional real routes and authorization checks for the completion work.
for path in ['/account-security','/qualifications','/screening-workflow','/agency-setup']:
 check('Completion screen '+path,admin.get(path)[0]==200)
admin.post('/select-project',{'job_id':data['a']})
admin.post('/qualifications',{'do':'type','name':'Test CDL clearance','expires_required':'1'})
_,qbody=admin.get('/qualifications')
type_id=re.search(r'<option value="(\d+)">Test CDL clearance</option>',qbody).group(1)
admin.post('/qualifications',{'do':'requirement','type_id':type_id})
_,qbody=admin.post('/roster',{'do':'status','placement_id':data['ids'][1]['placement'],'status':'confirmed'})
check('Missing project qualification blocks deployment','Current verified project qualifications' in qbody)
worker2.get('/qualifications')
worker2.post('/qualifications',{'do':'record','type_id':type_id,'expires_on':'2027-12-31','evidence_reference':'Test verified source','detail':'Class A'})
_,qbody=admin.get('/qualifications?candidate_id='+str(data['ids'][1]['candidate']))
qid=re.search(r'name="qualification_id" value="(\d+)"',qbody).group(1)
check('Worker qualification awaits staff review','pending' in qbody)
check('Worker cannot verify qualification',worker2.post('/qualifications',{'do':'review','qualification_id':qid,'status':'verified','note':'Bypass'})[0]==403)
admin.post('/qualifications?candidate_id='+str(data['ids'][1]['candidate']),{'do':'review','candidate_id':data['ids'][1]['candidate'],'qualification_id':qid,'status':'verified','note':'Evidence checked by agency'})
check('Qualification staff verification recorded','verified' in admin.get('/qualifications?candidate_id='+str(data['ids'][1]['candidate']))[1])
worker2.post('/qualifications',{'do':'record','type_id':type_id,'expires_on':'2020-01-01','evidence_reference':'Old source','detail':'Class A'})
check('Expired qualification cannot be verified',admin.post('/qualifications?candidate_id='+str(data['ids'][1]['candidate']),{'do':'review','candidate_id':data['ids'][1]['candidate'],'qualification_id':qid,'status':'verified','note':'Expired source'})[0]==422)
check('Workers do not see another qualification record','Test verified source' not in worker.get('/qualifications?candidate_id='+str(data['ids'][1]['candidate']))[1])

admin.post('/screening-workflow',{'do':'question','question':'Test availability question','required':'1'})
# An application still in play: historyApp has been accepted by now, and a
# settled application is refused for being settled rather than for the
# questionnaire, which is not what this test is for.
_,body=admin.post('/recruitment',{'do':'stage','application_id':data['contractApplications'][0],'stage':'offered','note':'Offer terms'})
check('Mandatory questionnaire blocks offer','Complete required screening questions' in body)
check('A settled application is refused for being settled',"is settled" in admin.post('/recruitment',{'do':'stage','application_id':data['historyApp'],'stage':'offered','note':'Offer terms'})[1])
_,body=worker.get('/screening-workflow?application_id='+str(data['historyApp']))
question_id=re.search(r'name="answer\[(\d+)\]"',body).group(1)
worker.post('/screening-workflow',{'do':'answers','application_id':data['historyApp'],f'answer[{question_id}]':'Available on Monday'})
check('Private candidate questionnaire recorded','Available on Monday' in admin.get('/screening-workflow?application_id='+str(data['historyApp']))[1])
check('Another worker cannot edit application answers',worker2.get('/screening-workflow?application_id='+str(data['historyApp']))[0]==404)
admin.post('/screening-workflow',{'do':'contact','application_id':data['historyApp'],'kind':'call','outcome':'Reached candidate','note':'Discussed shift availability','follow_up_at':'2026-10-20T10:00'})
check('Recruiter call and follow-up recorded','Discussed shift availability' in admin.get('/screening-workflow?application_id='+str(data['historyApp']))[1])
check('Client cannot access qualification documents',client.get('/qualifications')[0]==403)
admin.post('/hours',{'do':'import_attendance','week_ending':'2026-10-10'})
check('Approved attendance generates weekly hours','value="8"' in admin.get('/hours?week=2026-10-10')[1])
check('Google crawl sitemap route',public.get('/sitemap.xml')[0]==200)
check('Unsigned recruiting webhook rejected',public.post('/recruiting-webhook?channel=test_partner',{},False)[0]==401)
import time,hmac,hashlib,base64,struct
def signed_partner(body):
 stamp=str(int(time.time()));raw=json.dumps(body,separators=(',',':')).encode();signature=hmac.new(b'unit-test-secret-unit-test-secret',stamp.encode()+b'.'+raw,hashlib.sha256).hexdigest()
 request=urllib.request.Request(base+'/recruiting-webhook?channel=test_partner',raw,headers={'Content-Type':'application/json','X-Workforce-Timestamp':stamp,'X-Workforce-Signature':signature})
 try:
  with urllib.request.urlopen(request) as response:return response.status,response.read().decode()
 except urllib.error.HTTPError as error:return error.code,error.read().decode()
event={'schema':'workforce.application.v1','event_id':'fixture-42','vacancy_id':data['vac'],'name':'Partner candidate','email':'partner@test.invalid','consent':True}
status,body=signed_partner(event);check('Signed partner application received',status==201)
status,body=signed_partner(event);check('Repeated partner event deduplicated',status==200 and json.loads(body)['duplicate'])
status,body=signed_partner({**event,'name':'Changed candidate'});check('Changed duplicate event rejected',status==409)

recovery=Client();oldRecovery=Client();oldRecovery.login('recovery@test.invalid')
recovery.get('/recover?token='+data['recoveryToken'])
check('Password recovery completion',recovery.post('/recover',{'token':data['recoveryToken'],'password':'RecoveredPassword123!'})[0]==200)
check('Password recovery revokes old session','name="password"' in oldRecovery.get('/account')[1])
check('Recovery token cannot be reused','name="password"' not in recovery.get('/recover?token='+data['recoveryToken'])[1])
recovery.get('/login');recovery.post('/login',{'email':'recovery@test.invalid','password':'RecoveredPassword123!'})
recovery.post('/account-security',{'do':'start','password':'RecoveredPassword123!'})
_,body=recovery.get('/account-security');secret=re.search(r'<code[^>]*>([A-Z2-7]+)</code>',body).group(1)
def otp(step):
 key=base64.b32decode(secret+'='*((8-len(secret)%8)%8));digest=hmac.new(key,struct.pack('>Q',step),hashlib.sha1).digest();offset=digest[-1]&15;value=(struct.unpack('>I',digest[offset:offset+4])[0]&0x7fffffff)%1000000;return str(value).zfill(6)
# Enrolling with the previous step and signing in with the current one is
# what proves a code cannot be replayed. It only works if both requests
# land inside the same 30-second window as the server's own clock, so the
# sequence waits for a fresh window before it starts.
if time.time() % 30 > 20: time.sleep(31 - (time.time() % 30))
step=int(time.time())//30
_,body=recovery.post('/account-security',{'do':'enable','password':'RecoveredPassword123!','code':otp(step-1)})
check('Authenticator enrollment','Two-step verification enabled.' in body)
recovery_codes=re.findall(r'class="recovery-code">([A-F0-9-]+)</code>',body)
check('Recovery codes displayed once',len(recovery_codes)==8 and 'recovery-code' not in recovery.get('/account-security')[1])
recovery.post('/logout',{});recovery.get('/login')
_,body=recovery.post('/login',{'email':'recovery@test.invalid','password':'RecoveredPassword123!'})
check('Password alone does not bypass MFA','Authenticator code' in body)
_,body=recovery.post('/mfa',{'code':'000000'})
check('Invalid MFA code rejected','Invalid or expired authentication code.' in body)
_,body=recovery.post('/mfa',{'code':otp(step)})
check('Valid MFA code signs in','name="code"' not in body and 'recovery@test.invalid' in recovery.get('/account')[1])
recovery.post('/logout',{});recovery.get('/login');recovery.post('/login',{'email':'recovery@test.invalid','password':'RecoveredPassword123!'})
_,body=recovery.post('/mfa',{'code':otp(step)})
check('MFA code cannot replay','Invalid or expired authentication code.' in body)
_,body=recovery.post('/mfa',{'code':recovery_codes[0]})
check('Recovery code signs in', 'recovery@test.invalid' in recovery.get('/account')[1])
recovery.post('/logout',{});recovery.get('/login');recovery.post('/login',{'email':'recovery@test.invalid','password':'RecoveredPassword123!'})
_,body=recovery.post('/mfa',{'code':recovery_codes[0]})
check('Recovery code cannot replay','Invalid or expired authentication code.' in body)
talent=Client();talent.get('/join')
_,body=talent.upload('/join',{'name':'Future talent','email':'future@test.invalid','consent':'1'},'resume','resume.pdf',b'%PDF-1.4\nSynthetic resume\n%%EOF','application/pdf')
check('Talent pool receives encrypted resume','Application received' in body)
_,body=admin.get('/resumes');resume_id=re.search(r'/resumes\?download=(\d+)',body).group(1)
check('Worker cannot read unrelated resume',worker.get('/resumes?download='+resume_id)[0]==404)
check('Client cannot read resumes',client.get('/resumes')[0]==403)
talent2=Client();talent2.get('/join')
check('Executable resume rejected',talent2.upload('/join',{'name':'Invalid file','email':'invalidfile@test.invalid','consent':'1'},'resume','malware.exe',b'MZ fake executable','application/octet-stream')[0]==422)
visitor=Client();visitor.get('/join')
_,body=visitor.post('/language',{'locale':'fr','back':'/join'})
check('Public candidate can choose French','Rejoindre notre vivier' in body)
check('Public candidate language persists','Rejoindre notre vivier' in visitor.get('/join')[1])
admin.get('/offboarding')
admin.post('/offboarding',{'do':'requirement','title':'Test return checklist','instructions':'Confirm handover'})
_,body=worker2.get('/offboarding');requirement_id=re.search(r'name="requirement_id" value="(\d+)"',body).group(1)
_,body=admin.post('/roster',{'do':'status','placement_id':data['ids'][1]['placement'],'status':'completed'})
check('Unapproved offboarding blocks completion','Complete approved offboarding tasks' in body)
worker2.post('/offboarding',{'do':'submit','placement_id':data['ids'][1]['placement'],'requirement_id':requirement_id,'response':'Equipment and keys returned'})
admin.post('/offboarding',{'do':'review','placement_id':data['ids'][1]['placement'],'requirement_id':requirement_id,'status':'approved'})
check('Offboarding review stored','Equipment and keys returned' in admin.get('/offboarding')[1])
admin.get('/safety-plan?job_id='+str(data['a']))
admin.post('/safety-plan',{'job_id':data['a'],'access_instructions':'Test site gate','emergency_contacts':'Site coordinator','escalation_procedure':'Call supervisor','site_posts':'Main entrance'})
check('Worker can read assigned site safety plan','Test site gate' in worker.get('/safety-plan?job_id='+str(data['a']))[1])
check('Client cannot read private safety plan',client.get('/safety-plan?job_id='+str(data['a']))[0]==403)
check('Supervisor cannot read unrelated project safety plan',supervisor.get('/safety-plan?job_id='+str(data['otherJob']))[0]==404)
operational=Client();operational.login('admin@test.invalid');operational.post('/select-project',{'job_id':data['a']})
operational.get('/imports')
sheet=b'Name,Email,Employee,ADP,Type,Payment,Start,Shift,Pay,Bill\nImport extended,extended@test.invalid,EXT42,ADP42,hourly,check,2026-10-01,Day,35,70\n'
_,body=operational.upload('/imports',{'do':'preview'},'sheet','extended.csv',sheet,'text/csv')
mapping={'mapping[full_name]':0,'mapping[email]':1,'mapping[employee_number]':2,'mapping[adp_employee_id]':3,'mapping[employment_type]':4,'mapping[payment_method]':5,'mapping[start_date]':6,'mapping[shift]':7,'mapping[pay_rate]':8,'mapping[bill_rate]':9,'mapping[trade]':''}
operational.post('/imports',{'do':'commit',**mapping})
_,body=operational.get('/employees?q=extended@test.invalid');extended_id=re.search(r'/employee-folder\?id=(\d+)',body).group(1)
_,body=operational.get('/employee-folder?id='+extended_id)
check('Extended spreadsheet ADP and employee mapping','ADP42' in body and 'EXT42' in body)
operational.get('/onboarding')
_,body=operational.post('/onboarding',{'do':'configure_requirement','requirement_id':data['req'],'instructions':'Updated approved safety instruction','required':'1'})
check('Project onboarding instructions editable','Updated approved safety instruction' in body)
_,body=operational.post('/roster',{'do':'status','placement_id':data['ids'][0]['placement'],'status':'on_site'})
_,body=worker.get('/portal')
check('Updated instructions require fresh review',bool(re.search(r'Updated approved safety instruction</p><span class="tag">pending',body)))
status,manifest=public.get('/app-manifest')
check('Public mobile manifest available',status==200 and len(json.loads(manifest)['icons'])>=2)
with public.opener.open(base+'/assets/app-icon-192.png') as icon_response:
 check('Mobile app icon available',icon_response.status==200 and icon_response.read().startswith(b'\x89PNG'))

operational.get('/contracts');operational.post('/language',{'locale':'en','back':'/contracts'})
check('DocuSign webhook disabled in staging',public.post('/docusign-webhook',{},csrf=False)[0]==503)
check('Client cannot access employment contracts',client.get('/contracts')[0]==403)
worker2.get('/contracts?id='+str(data['expiredContract']));_,body=worker2.post('/contracts',{'do':'sign','contract_id':data['expiredContract'],'signer_name':'Test','consent':'1','content_hash':hashlib.sha256(b'Expired terms').hexdigest()})
check('Expired contract cannot be signed','Contract has expired.' in body)
operational.post('/contracts',{'do':'policy','method':'internal','required':'1','document_types':'Contract identity proof'})
app0,app1,app2,app3=data['contractApplications']
for application,account in [(app0,worker),(app1,worker2),(app2,worker),(app3,worker2)]:
 account.get('/screening-workflow?application_id='+str(application));account.post('/screening-workflow',{'do':'answers','application_id':application,f'answer[{question_id}]':'Available for contract test'})
operational.get('/contracts')
_,body=operational.post('/contracts',{'do':'draft','application_id':app0,'title':'Verified contract','terms':'Synthetic contract terms','days':'14'})
check('Missing approved documents block contract draft','Approve required documents before preparing the contract.' in body)
_,body=operational.post('/recruitment',{'do':'stage','application_id':app0,'stage':'offered','note':'Attempted legacy bypass'})
check('Legacy offer cannot bypass contract document policy','Use the contract workflow after required document verification.' in body)
def approve_contract_proof(account):
 account.get('/proofs');account.upload('/proofs',{'do':'upload','document_type':'Contract identity proof'},'proof','identity.pdf',b'%PDF-1.4\nSynthetic identity proof\n%%EOF','application/pdf')
 operational.get('/proofs');_,proofbody=operational.get('/proofs');proofid=re.search(r'name="document_id" value="(\d+)"',proofbody).group(1)
 operational.post('/proofs',{'do':'review','document_id':proofid,'status':'approved','review_note':'Synthetic verification for regression'})
 return proofid
proof0=approve_contract_proof(worker);proof1=approve_contract_proof(worker2)
def create_contract(application,title):
 operational.get('/contracts');_,body=operational.post('/contracts',{'do':'draft','application_id':application,'title':title,'terms':'Synthetic contract terms for '+title,'days':'14'})
 match=re.search(r'name="contract_id" value="(\d+)"',body);assert match,body[:2000]
 return match.group(1)
contract0=create_contract(app0,'Verified contract')
operational.get('/roster');_,deploymentbody=operational.post('/roster',{'do':'status','placement_id':data['ids'][0]['placement'],'status':'on_site'})
check('Unsigned current contract blocks deployment','A signed current contract is required before deployment.' in deploymentbody)
check('Candidate cannot view an unissued draft',worker.get('/contracts?id='+contract0)[0]==404)
operational.get('/contracts?id='+contract0)
_,attachmentbody=operational.upload('/contracts',{'do':'attach','contract_id':contract0},'contract_pdf','original.pdf',b'%PDF-1.4\nSynthetic original contract\n%%EOF','application/pdf')
check('Draft original PDF stored privately','Download' in attachmentbody and 'Original attached' in attachmentbody)
operational.post('/contracts',{'do':'approve','contract_id':contract0})
operational.get('/proofs');operational.post('/proofs',{'do':'review','document_id':proof0,'status':'rejected','review_note':'Reverification needed'})
operational.get('/contracts?id='+contract0);_,body=operational.post('/contracts',{'do':'issue','contract_id':contract0})
check('Revoked proof approval blocks contract issuance','Complete document and screening reviews before issuing the contract.' in body)
operational.get('/proofs');operational.post('/proofs',{'do':'review','document_id':proof0,'status':'approved','review_note':'Reverified'})
operational.get('/contracts?id='+contract0);operational.post('/contracts',{'do':'issue','contract_id':contract0})
_,body=worker.get('/contracts?id='+contract0)
check('Issued contract can be reviewed in private portal','Synthetic contract terms for Verified contract' in body and 'Sign contract' in body)
check('Other employee cannot read contract',worker2.get('/contracts?id='+contract0)[0]==404)
contracthash=re.search(r'name="content_hash" value="([a-f0-9]+)"',body).group(1)
_,body=worker.post('/contracts',{'do':'sign','contract_id':contract0,'signer_name':'Test worker','content_hash':'0'*64,'consent':'1'})
check('Contract signing rejects changed content hash','Read the current contract' in body)
worker.get('/portal');_,body=worker.post('/portal',{'do':'accept_offer','application_id':app0,'signer_name':'Test worker','consent':'1'})
check('Legacy acceptance cannot bypass contract workflow','Review and sign the current contract' in body and 'Synthetic contract terms for Verified contract' not in body)
worker.get('/contracts?id='+contract0);_,body=worker.post('/contracts',{'do':'sign','contract_id':contract0,'signer_name':'Test worker','content_hash':contracthash,'consent':'1'})
check('Internal contract signature records signer and archive','Signed by Test worker on' in body and 'Sign contract</button>' not in body)
check('Other employee cannot read signature record',worker2.get('/contracts?receipt='+contract0)[0]==404)
_,record=worker.get('/contracts?receipt='+contract0)
check('Signature record preserves consent and exact content hash',json.loads(record)['content_hash']==contracthash and any(e['action']=='electronic_consent' for e in json.loads(record)['events']))
worker.post('/contracts',{'do':'sign','contract_id':contract0,'signer_name':'Different name','content_hash':contracthash,'consent':'1'})
check('Signed contract cannot be signed twice','Signed by Test worker on' in worker.get('/contracts?id='+contract0)[1])
operational.get('/contracts?id='+contract0);_,body=operational.post('/contracts',{'do':'void','contract_id':contract0})
check('Signed contract is immutable','A signed contract cannot be changed.' in body)
contract1=create_contract(app1,'Uploaded contract');operational.post('/contracts',{'do':'approve','contract_id':contract1});operational.post('/contracts',{'do':'issue','contract_id':contract1})
worker2.get('/contracts?id='+contract1);_,body=worker2.upload('/contracts',{'do':'upload_signed','contract_id':contract1},'signed_pdf','signed.pdf',b'%PDF-1.4\nSynthetic signed contract\n%%EOF','application/pdf')
check('Uploaded signature awaits staff review','awaiting verification' in body and 'Signed by' not in body)
operational.get('/contracts?id='+contract1);_,body=operational.post('/contracts',{'do':'approve_upload','contract_id':contract1,'review_note':'Synthetic signed PDF and identity checked'})
check('Staff signature verification completes contract','Synthetic signed PDF and identity checked' in body and 'Signed by' in body)
contractfile=re.search(r'/contracts\?download=(\d+)',body).group(1)
check('Other worker cannot download signed PDF',worker.get('/contracts?download='+contractfile)[0]==404)
with worker2.opener.open(base+'/contracts?download='+contractfile) as pdf:
 check('Owner downloads archived signed PDF',pdf.read().startswith(b'%PDF-'))
contract2=create_contract(app2,'Declined contract');operational.post('/contracts',{'do':'approve','contract_id':contract2});operational.post('/contracts',{'do':'issue','contract_id':contract2})
worker.get('/contracts?id='+contract2);worker.post('/contracts',{'do':'decline','contract_id':contract2,'reason':'Terms need revision'})
check('Candidate can decline contract','Declined' in worker.get('/contracts?id='+contract2)[1])
contract2revision=create_contract(app2,'Revised contract')
check('New contract revision preserves history',contract2revision!=contract2 and 'Declined contract' in operational.get('/contracts')[1])
operational.post('/contracts',{'do':'policy','method':'docusign','required':'1','document_types':'Contract identity proof'})
contract3=create_contract(app3,'Provider contract');operational.post('/contracts',{'do':'approve','contract_id':contract3})
_,body=operational.post('/contracts',{'do':'send_provider','contract_id':contract3})
check('DocuSign staging sends nothing while disabled','DocuSign is disabled or not configured.' in body)
worker.get('/contracts');policy_status,body=worker.post('/contracts',{'do':'policy','method':'internal','document_types':''})
check('Worker cannot change contract policy',policy_status==403)
operational.get('/contracts');operational.post('/language',{'locale':'fr','back':'/contracts'})
check('Contract workspace translated in French','Contrats et signatures' in operational.get('/contracts')[1])
operational.post('/language',{'locale':'es','back':'/contracts'})
check('Contract workspace translated in Spanish','Contratos y firmas' in operational.get('/contracts')[1])
operational.post('/language',{'locale':'en','back':'/contracts'})

for count in range(11):
 _,body=public.post('/login',{'email':'absent@test.invalid','password':'Invalid password'})
check('Repeated invalid logins remain generic','That email and password do not match an account.' in body)

json.dump(results,open('work/test-results.json','w'),indent=2)

