<div class="page-heading"><div><span class="eyebrow"><?= te('CLIENT WORKSPACE') ?></span><h1><?= te('Your project workforce') ?></h1><p class="sub"><?= te('Review deployed teams, approved attendance and issued invoices.') ?></p></div></div>
<?php if($project): ?><section class="card"><h2><?= te('Deployment logistics') ?></h2><div class="grid g4"><?php foreach(['rooms'=>'Rooms reserved','flights'=>'Flights booked','vehicles'=>'Vehicles out','equipment'=>'Equipment outstanding'] as $metric=>$label): ?><div><span class="muted"><?= te($label) ?></span><h2><?= (int)$logistics[$metric] ?></h2></div><?php endforeach; ?></div><?php if($clientEquipment): ?><h3><?= te('Client-owned equipment') ?></h3><div class="scroll"><table><tr><th><?= te('Equipment') ?></th><th><?= te('Asset tag') ?></th><th><?= te('Serial number') ?></th><th><?= te('Employee') ?></th><th><?= te('Returned') ?></th></tr><?php foreach($clientEquipment as $asset): ?><tr><td><?= e($asset['name']) ?></td><td><?= e($asset['asset_tag']) ?></td><td><?= e($asset['serial_number']) ?></td><td><?= e($asset['full_name']) ?></td><td><?= $asset['returned_at']?e(d($asset['returned_at'])):te('Pending') ?></td></tr><?php endforeach; ?></table></div><?php endif; ?></section><?php endif; ?>
<?php if($invoice): ?><section class="card invoice-print"><h2><?= te('Invoice') ?> <?= e($invoice['reference']) ?></h2><p><?= e($project['client_name'].' · '.$project['title']) ?></p><p><?= e(d($invoice['starts_on']).' — '.d($invoice['ends_on'])) ?></p><div class="scroll"><table><thead><tr><th><?= te('Employee') ?></th><th><?= te('Week') ?></th><th><?= te('Hours') ?></th><th><?= te('Client rate') ?></th><th><?= te('Total') ?></th></tr></thead><tbody><?php foreach($invoiceLines as $line): ?><tr><td><?= e($line['worker']) ?></td><td><?= e(d($line['week'])) ?></td><td><?= e($line['hours']) ?></td><td><?= e(money_local($line['rate'])) ?></td><td><?= e(money_local($line['amount'])) ?></td></tr><?php endforeach; ?></tbody></table></div><p><strong><?= te('Total') ?> <?= e(money_local($invoice['total'])) ?></strong></p><button type="button" class="btn" onclick="window.print()"><?= te('Print invoice') ?></button></section><?php endif; ?>
<?php if(!$projects): ?><div class="card"><?= te('No authorized projects. Contact your agency administrator.') ?></div><?php else: ?>
<form method="get" class="card row"><label><?= te('Project') ?></label><select name="job_id"><?php foreach($projects as $choice): ?><option value="<?= (int)$choice['id'] ?>" <?= (int)$choice['id']===$jobId?'selected':'' ?>><?= e($choice['title'].' · '.$choice['client_name']) ?></option><?php endforeach; ?></select><button class="btn"><?= te('Open project') ?></button></form>
<div class="grid g3"><div class="stat"><div class="l"><?= te('Workers on site') ?></div><div class="n"><?= $onSite ?></div></div><div class="stat"><div class="l"><?= te('Approved attendance records') ?></div><div class="n"><?= $attendanceCount ?></div></div><div class="stat"><div class="l"><?= te('Issued invoices') ?></div><div class="n"><?= $invoiceCount ?></div></div></div>
<div class="card scroll"><h2><?= e($project['title'].' · '.$project['site_city'].' · '.$project['site_state']) ?></h2><table><thead><tr><th><?= te('Employee') ?></th><th><?= te('Trade') ?></th><th><?= te('Shift') ?></th><th><?= te('Supervisor') ?></th><th><?= te('Status') ?></th></tr></thead><tbody><?php foreach($crew as $worker): ?><tr><td><?= e($worker['full_name']) ?></td><td><?= e($worker['trade']) ?></td><td><?= e($worker['shift_label']) ?></td><td><?= e($worker['supervisor']) ?></td><td><?= te($worker['status']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="card scroll"><h2><?= te('Approved attendance') ?></h2><form method="get" class="row"><input type="hidden" name="job_id" value="<?= $jobId ?>"><input type="hidden" name="export" value="attendance"><label><?= te('From') ?></label><input type="date" name="from" value="<?= date('Y-m-01') ?>" required><label><?= te('To') ?></label><input type="date" name="to" value="<?= date('Y-m-d') ?>" required><button class="btn ghost sm"><?= te('Export attendance') ?></button></form><p class="muted"><?= te('Client confirmation does not alter payroll approval or wages.') ?></p><table><thead><tr><th><?= te('Date') ?></th><th><?= te('Employee') ?></th><th><?= te('Hours') ?></th><th><?= te('Client review') ?></th></tr></thead><tbody><?php foreach($attendance as $record): ?><tr><td><?= e(d($record['work_date'])) ?></td><td><?= e($record['full_name']) ?></td><td><?= e($record['hours']) ?></td><td><form method="post"><?= csrf_field() ?><input type="hidden" name="job_id" value="<?= $jobId ?>"><input type="hidden" name="attendance_id" value="<?= (int)$record['id'] ?>"><select name="decision"><option value="confirmed" <?= ($record['decision'] ?? '')==='confirmed'?'selected':'' ?>><?= te('confirmed') ?></option><option value="disputed" <?= ($record['decision'] ?? '')==='disputed'?'selected':'' ?>><?= te('disputed') ?></option></select><input name="note" maxlength="1000" value="<?= e($record['note'] ?? '') ?>" placeholder="<?= te('Review note') ?>"><button class="btn sm"><?= te('Save review') ?></button></form></td></tr><?php endforeach; ?></tbody></table></div>
<div class="card scroll"><h2><?= te('Issued invoices') ?></h2><table><thead><tr><th><?= te('Reference') ?></th><th><?= te('Period') ?></th><th><?= te('Total') ?></th><th><?= te('Status') ?></th></tr></thead><tbody><?php foreach($invoices as $invoice): ?><tr><td><a href="/client-portal?job_id=<?= $jobId ?>&amp;invoice_id=<?= (int)$invoice['id'] ?>"><?= e($invoice['reference']) ?></a></td><td><?= e(d($invoice['starts_on']).' — '.d($invoice['ends_on'])) ?></td><td><?= e(money_local($invoice['total'])) ?></td><td><?= te($invoice['status']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php endif; ?>

<section class="card"><h2><?= te('Client requests') ?></h2><?php foreach($orders as $request): ?><p><b><?= e($request['title']) ?></b> · <?= te($request['status']) ?> · <?= te($request['source']) ?></p><p><?= e($request['description']) ?></p><?php endforeach; ?></section>

<nav class="card" aria-label="<?= te('Reports') ?>">
<?php foreach(['crew_page'=>['Employee',$crewPage,$crewCount],'attendance_page'=>['Attendance',$attendancePage,$attendanceCount],'invoice_page'=>['Issued invoices',$invoicePage,$invoiceCount],'request_page'=>['Client requests',$requestPage,$requestCount]] as $parameter=>$paging): ?>
<p><b><?= te($paging[0]) ?></b> · <?= te(':count records · page :page',['count'=>$paging[2],'page'=>$paging[1]]) ?>
<?php if($paging[1]>1): ?><a class="btn ghost sm" href="/client-portal?<?= e(http_build_query(['job_id'=>$jobId,$parameter=>$paging[1]-1])) ?>"><?= te('Previous page') ?></a><?php endif; ?>
<?php if($paging[1]*100<$paging[2]): ?><a class="btn ghost sm" href="/client-portal?<?= e(http_build_query(['job_id'=>$jobId,$parameter=>$paging[1]+1])) ?>"><?= te('Next page') ?></a><?php endif; ?></p>
<?php endforeach; ?></nav>
<style>@media print{.top,.nav,form,button,.sub{display:none!important}.wrap{margin:0;padding:0}.card{box-shadow:none}.wrap> :not(.invoice-print){display:none!important}.invoice-print{display:block!important}}</style>
