<p><a class="btn ghost" href="/contracts"><?= te('Contracts & signatures') ?></a></p><p><?= te('Employee number') ?>: <?= e($profile['employee_number']??'') ?></p>
<h1>Employee folder · <?= e($c['full_name']) ?></h1><p class="sub"><?= te('Persistent identity, applications, assignments, credentials and audit history across projects.') ?></p><div class="grid g2"><div class="card"><h2><?= te('Employee profile') ?></h2><p><?= e($c['email'].' · '.$c['phone']) ?></p><p><?= e($profile['employment_type'].' · '.$profile['availability'].' · rehire '.$profile['rehire_status']) ?></p><?php if(can('recruiter')): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="do" value="profile"><input type="hidden" name="candidate_id" value="<?= $cid ?>"><label><?= te('Employment category') ?></label><select name="employment_type"><?php foreach(['hourly','salaried','contractor','external'] as $x): ?><option <?= $x===$profile['employment_type']?'selected':'' ?>><?= e($x) ?></option><?php endforeach; ?></select><label><?= te('Availability') ?></label><select name="availability"><?php foreach(['available','unavailable','on_assignment'] as $x): ?><option <?= $x===$profile['availability']?'selected':'' ?>><?= e($x) ?></option><?php endforeach; ?></select><label><?= te('Rehire assessment') ?></label><select name="rehire_status"><?php foreach(['review','eligible','ineligible'] as $x): ?><option <?= $x===$profile['rehire_status']?'selected':'' ?>><?= e($x) ?></option><?php endforeach; ?></select><button class="btn"><?= te('Save profile') ?></button></form><?php endif; ?></div>

<?php if(can('payroll')): ?><form class="card" method="post"><?= csrf_field() ?><input type="hidden" name="do" value="payment"><input type="hidden" name="candidate_id" value="<?= $cid ?>"><h2><?= te('Payroll setup') ?></h2><label><?= te('Payment method') ?></label><select name="payment_method"><?php foreach(['direct_deposit','check','cash'] as $x): ?><option <?= $x===$profile['payment_method']?'selected':'' ?>><?= e($x) ?></option><?php endforeach; ?></select><label><?= te('ADP employee ID') ?></label><input name="adp_employee_id" value="<?= e($profile['adp_employee_id']) ?>"><label><?= te('Salary per payroll period · salaried workers') ?></label><input type="number" min="0" step="0.01" name="salary_per_period" value="<?= e($profile['salary_per_period']) ?>"><button class="btn"><?= te('Save payment setup') ?></button><p class="muted"><?= te('No bank account data is entered here. Use the approved ADP enrollment process.') ?></p></form><?php endif; ?></div>

<div class="card"><h2><?= te('Assignment history') ?></h2><?php foreach($placements as $a): ?><p><?= e($a['title'].' · '.$a['trade'].' · '.$a['status'].' · '.$a['start_date'].' → '.$a['end_date'].' · '.$a['supervisor']) ?></p><?php endforeach; ?></div><div class="card"><h2><?= te('Application history') ?></h2><?php foreach($applications as $a): ?><p><?= e($a['title'].' · '.$a['stage'].' · '.$a['created_at']) ?></p><?php endforeach; ?></div>

<form class="card" method="post"><?= csrf_field() ?><input type="hidden" name="do" value="credential"><input type="hidden" name="candidate_id" value="<?= $cid ?>"><h2><?= te('Add credential / driver licence') ?></h2><label><?= te('Type · use driver_license for driving eligibility') ?></label><input name="credential_type" required maxlength="120"><label><?= te('Description / class (e.g. CDL)') ?></label><input name="description" maxlength="255"><label><?= te('Expiry date') ?></label><input name="expires_on" type="date" required><label><?= te('Supporting uploaded proof') ?></label><select name="document_id"><option value=""><?= te('No proof yet') ?></option><?php foreach($docs as $d): ?><option value="<?= (int)$d['id'] ?>"><?= e($d['document_type']) ?></option><?php endforeach; ?></select><button class="btn"><?= te('Submit credential') ?></button></form><div class="card"><h2><?= te('Credentials') ?></h2><?php foreach($credentials as $d): ?><form class="row" method="post"><?= csrf_field() ?><input type="hidden" name="do" value="review_credential"><input type="hidden" name="candidate_id" value="<?= $cid ?>"><input type="hidden" name="credential_id" value="<?= (int)$d['id'] ?>"><span><?= e($d['credential_type'].' · '.$d['expires_on'].' · '.$d['status']) ?></span><?php if(can('recruiter')): ?><select name="status"><option value="verified"><?= te('verified') ?></option><option value="rejected"><?= te('rejected') ?></option></select><button class="btn sm"><?= te('Review') ?></button><?php endif; ?></form><?php endforeach; ?></div>

<div class="card"><h2><?= te('Document index') ?></h2><?php foreach($docs as $d): ?><p><?= e($d['document_type'].' · '.$d['status'].' · '.$d['created_at']) ?></p><?php endforeach; ?></div><div class="card"><h2><?= te('Traceability') ?></h2><?php foreach($events as $e): ?><p><?= e($e['created_at'].' · '.$e['name'].' · '.$e['event_type'].' · '.$e['detail']) ?></p><?php endforeach; ?></div><div class="card"><h2><?= te('Signed document history') ?></h2><?php foreach($signatures as $s): ?><p><?= e($s['title'].' · '.$s['status'].' · '.$s['signer_name'].' · '.$s['signed_at']) ?></p><?php endforeach; ?></div><?php if(!$own): ?><div class="card"><h2><?= te('Operational audit history') ?></h2><?php foreach($history as $h): ?><p><?= e($h['created_at'].' · '.$h['name'].' · '.$h['action'].' · '.$h['detail']) ?></p><?php endforeach; ?></div><?php endif; ?>

<?php if(!$own): ?><div class="card"><h2><?= te('Recruitment decisions') ?></h2><?php foreach($applicationHistory as $event): ?><p><?= e($event['created_at'].' · '.$event['title'].' · '.$event['stage'].' · '.$event['name'].' · '.$event['note']) ?></p><?php endforeach; ?></div><?php endif; ?>


<p><a class="btn ghost" href="/qualifications?candidate_id=<?= (int)$cid ?>"><?= te('Qualifications & expiry') ?></a></p>

<p><a class="btn ghost" href="/resumes?candidate_id=<?= (int)$cid ?>"><?= te('Candidate resumes') ?></a></p>
