<h1><?= te('Recruitment and onboarding') ?></h1>
<?php if($inviteUrl): ?><div class="card"><h2><?= te('Private invitation · expires in 48 hours') ?></h2><p><?= te('Send this link directly to the candidate through your approved communication channel.') ?></p><input readonly value="<?= e($inviteUrl) ?>"></div><?php endif; ?>
<div class="grid g2"><form method="post" class="card"><?= csrf_field() ?><input type="hidden" name="do" value="invite"><h2><?= te('Invite candidate to private portal') ?></h2><p class="small muted" style="margin:-6px 0 12px"><?= te('They get a link to sign in, see their offer, their tasks and their travel.') ?></p><label for="inv-who"><?= te('Who') ?></label><select id="inv-who" name="candidate_id" required><option value=""><?= te('Choose somebody…') ?></option><?php foreach($people as $person): ?><option value="<?= (int)$person['id'] ?>"><?= e($person['full_name']) ?><?php if($person['city']): ?> &middot; <?= e(trim($person['city'].' '.$person['state'])) ?><?php endif; ?></option><?php endforeach; ?></select><button class="btn"><?= te('Generate invitation') ?></button></form>
<form method="post" class="card"><?= csrf_field() ?><input type="hidden" name="do" value="requirement"><h2><?= te('Add project requirement') ?></h2><label><?= te('Task name') ?></label><input name="title" maxlength="190" required><label><?= te('Instructions / approved provider link') ?></label><textarea name="instructions"></textarea><p class="small muted"><?= te('Use an approved I-9, tax-form or document provider for sensitive paperwork. This task tracker does not collect those documents.') ?></p><button class="btn"><?= te('Add requirement') ?></button></form></div>
<div class="card"><h2><?= te('Worker tasks') ?></h2><?php foreach($tasks as $t): ?><form class="row" method="post"><?= csrf_field() ?><input type="hidden" name="do" value="review"><input type="hidden" name="task_id" value="<?= (int)$t['id'] ?>"><span><?= e($t['full_name'].' · '.$t['title'].' · '.$t['status']) ?></span><span><?= e($t['response']) ?></span><select name="status"><option value="approved"><?= te('approved') ?></option><option value="rejected"><?= te('rejected') ?></option></select><button class="btn sm"><?= te('Review') ?></button></form><?php endforeach; ?></div>
<div class="card"><h2><?= te('Application QR codes') ?></h2><p><?= te('Create and manage requisitions in your recruiting workspace.') ?></p><a class="btn" href="/requisitions"><?= te('Open requisitions') ?></a></div>
<div class="card tight"><div style="padding:14px 18px;border-bottom:1px solid var(--line)"><h2 style="margin:0"><?= te('Applications on this project') ?></h2><p class="small muted" style="margin:4px 0 0"><?= te('Invite somebody above once they have an offer, so they can see it and work their tasks.') ?></p></div><?php if(!$applications): ?><div class="empty"><?= te('No applications on this project yet.') ?></div><?php else: ?><?php $appWords = ['new'=>'New','screening'=>'Screening','interview'=>'Interview','offered'=>'Offered','accepted'=>'Accepted','rejected'=>'Rejected','withdrawn'=>'Withdrawn']; ?><div class="scroll"><table><thead><tr><th><?= te('Person') ?></th><th><?= te('Applied for') ?></th><th><?= te('Stage') ?></th></tr></thead><tbody><?php foreach($applications as $a): ?><tr><td><a href="/candidates/<?= (int)$a['candidate_id'] ?>"><?= e($a['full_name']) ?></a></td><td class="small"><?= e($a['title']) ?></td><td><span class="tag <?= in_array($a['stage'],['accepted'],true)?'green':(in_array($a['stage'],['rejected','withdrawn'],true)?'red':(in_array($a['stage'],['offered','interview'],true)?'amber':'grey')) ?>"><?= te($appWords[$a['stage']] ?? $a['stage']) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>

<div class="card"><h2><?= te('Configure project instructions') ?></h2><?php foreach($requirements as $requirement): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="do" value="configure_requirement"><input type="hidden" name="requirement_id" value="<?= (int)$requirement['id'] ?>"><h3><?= e($requirement['title']) ?></h3><label><?= te('Approved instructions') ?><textarea name="instructions" required maxlength="8000"><?= e($requirement['instructions']) ?></textarea></label><label><input name="required" type="checkbox" style="width:auto" <?= $requirement['required']?'checked':'' ?>> <?= te('Required') ?></label><button class="btn ghost"><?= te('Save instructions') ?></button></form><?php endforeach; ?></div>
